### ISSUE TITLE
press super and open menu in openbox

### ISSUE THREAD

**Issue by arcolinuxz** [arcolinux/arcolinux-openbox-configs#1]
install xcape
in autostart
xcape -e 'Super_L=Super_L|space'

**Comment by arcolinuxz** [comment]
tested and works

sudo pacman -S xcape 
@deadsidestar  could you check 
I am all for to put it in there

**Comment by arcolinuxz** [comment]
add it in then?

**Comment by deadsidestar** [comment]
I'm in to add it

**Comment by arcolinuxz** [comment]
done with hashtag out
if not installed then error
